server:
  port: 8084

spring:
  datasource:
    username: root
    password: 721251
    url: jdbc:mysql://localhost:3306/ShanruanShopping?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB





